Provide option to auto fix code from linting tools

diff --git a/code-formatter/Dockerfile b/code-formatter/Dockerfile
--- a/code-formatter/Dockerfile
+++ b/code-formatter/Dockerfile
@@ -12,6 +12,7 @@ FROM alpine:3.16.0@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1ac
 
 WORKDIR /usr/local/src/code-formatter
 RUN <<BUILD_DEPENDENCIES
+# Install black, nodejs, and npm
 set -o errexit
 apk update
 apk add --no-cache \
@@ -39,7 +40,10 @@ su code_formatter -c '/usr/local/src/code-formatter/bin/pip install --disable-pi
 # can be picked up by vulnerability scans easier.
 su code_formatter -c '/usr/local/src/code-formatter/bin/pip freeze > /usr/local/src/code-formatter/requirements.txt'
 
+# Use whatever nodejs version that is available for this Alpine Linux version.
 apk add --no-cache nodejs npm
+
+# Don't need these packages after installing black.
 apk --purge del \
   gcc \
   python3-dev \
@@ -51,6 +55,7 @@ BUILD_DEPENDENCIES
 WORKDIR /home/code_formatter
 
 RUN <<NPM_INSTALL
+# Install eslint, prettier, stylelint tools with npm.
 set -o errexit
 node --version
 npm --version
@@ -60,7 +65,6 @@ npm --version
 # Check each one listed on https://socket.dev/
 # https://socket.dev/npm/package/eslint/overview/8.20.0
 # https://socket.dev/npm/package/eslint-config-prettier/overview/8.5.0
-# https://socket.dev/npm/package/eslint-plugin-prettier/overview/4.2.1
 # https://socket.dev/npm/package/prettier/overview/2.7.1
 # https://socket.dev/npm/package/stylelint/overview/14.9.1
 # https://socket.dev/npm/package/stylelint-config-standard/overview/26.0.0
@@ -70,7 +74,6 @@ cat <<HERE > package.json
   "dependencies": {
     "eslint": "8.20.0",
     "eslint-config-prettier": "8.5.0",
-    "eslint-plugin-prettier": "4.2.1",
     "prettier": "2.7.1",
     "stylelint": "14.9.1",
     "stylelint-config-standard": "26.0.0",
@@ -96,32 +99,60 @@ COPY --chown=code_formatter:code_formatter .stylelintrc.json ./
 COPY --chown=code_formatter:code_formatter .modified-files.tar ./
 
 RUN <<FORMAT
+# Run prettier and black on modified files.
 set -o errexit
 su code_formatter -c 'mkdir -p /home/code_formatter/code'
 su code_formatter -c 'tar x -f /home/code_formatter/.modified-files.tar \
   -C /home/code_formatter/code'
+chown -R code_formatter:code_formatter code
 
-su code_formatter -c 'npx eslint --fix \
-  --no-error-on-unmatched-pattern --exit-on-fatal-error \
-  --output-file eslint_errors.log --format unix \
-  code || printf "ERROR with eslint"'
-touch eslint_errors.log
-sed -i 's^/home/code_formatter/code/^^' eslint_errors.log
+su code_formatter -c 'npx prettier --write code'
 
-su code_formatter -c 'npx stylelint --fix --formatter unix "code/**/*.css" > stylelint_errors.log || printf ""'
-
-su code_formatter -c 'npx prettier --write code || printf ""'
-
-su code_formatter -c '/usr/local/src/code-formatter/bin/black code || printf ""'
+su code_formatter -c '/usr/local/src/code-formatter/bin/black code'
 
 FORMAT
 
+ARG LINT_AUTO_FIX=no
+RUN <<LINT
+# Run linting tools on formatted code and create error log files.
+set -o errexit
+if [ "$LINT_AUTO_FIX" = "yes" ]; then
+  set -- "--fix"
+else
+  set --
+fi
+su code_formatter -c 'npx eslint \
+  "$@" \
+  --no-error-on-unmatched-pattern --exit-on-fatal-error \
+  --output-file eslint_errors.log --format unix \
+  code || printf "eslint errors"'
+touch eslint_errors.log
+sed -i 's^/home/code_formatter/code/^^' eslint_errors.log
+
+if [ "$LINT_AUTO_FIX" = "yes" ]; then
+  set -- "--fix"
+else
+  set --
+fi
+su code_formatter -c 'npx stylelint "$@" --formatter unix "code/**/*.css" > stylelint_errors.log || printf ""'
+touch stylelint_errors.log
+sed -i 's^/home/code_formatter/code/^^' stylelint_errors.log
+
+LINT
+
 USER code_formatter
 
-FROM scratch as formatted-files
+# Only care about the files from the build stage that were made.
+FROM scratch as output-files
+
+# Include these for further analysis.
 COPY --from=build /usr/local/src/code-formatter/requirements.txt /code-formatter/requirements.txt
 COPY --from=build /home/code_formatter/package-lock.json /code-formatter/package-lock.json
+
+# The log files are useful to know which files have errors or other suggested fixes.
 COPY --from=build /home/code_formatter/eslint_errors.log /
 COPY --from=build /home/code_formatter/stylelint_errors.log /
 
+# Include all the files that were updated so the user has the option to
+# overwrite as needed.
 COPY --from=build /home/code_formatter/code/ /
